services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
  rabbitMQ:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      # - rabbitMQ