services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
  rabbitMQ:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - APP_PORT=80
    ports:
      - "5000:80"
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      redis :
        condition: service_started
      rabbitMQ:
        condition: service_healthy
      
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    volumes:
      - ./consumer:/app
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitMQ:
        condition: service_healthy
      redis :
        condition: service_started