tf-init:
	docker run --rm -v .:/foundation -w /foundation hashicorp/terraform:latest init
tf-fmt:
	docker run --rm -v .:/foundation -w /foundation hashicorp/terraform:latest fmt
tf-validate:
	docker run --rm -v .:/foundation -w /foundation hashicorp/terraform:latest validate
tf-plan:
	docker run --rm -v .:/foundation -w /foundation hashicorp/terraform:latest plan  