name: Moon

on:
  workflow_dispatch:

run-name: Boutton Appuyé 

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name : curl
        uses: enflo/curl-action@master
        with:
          curl: "https://wttr.in/Moon"