apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: api
    soft: waitress
  name: fakeworks-api-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pods-api
      app.kubernetes.io/name: pods-api
      soft: waitress
  template:
    metadata:
      labels:
        app: pods-api
        app.kubernetes.io/name: pods-api
        soft: waitress
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/bidet-toigo-api:latest
        name: pods-api
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "4m"
            memory: "32Mi"
        env:
        - name: APP_PORT
          value: "80"
        - name: RABBITMQ_HOST
          value: svc-rabbitmq
        - name: REDIS_HOST
          value: svc-redis