apiVersion: v1
kind: Service
metadata:
  name: svc-api
  labels:
    app.kubernetes.io/name: pods-api
    
spec:
  selector:
    app.kubernetes.io/name: pods-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80